# Change these first
owner: mohorojo # Your GitHub username
repo: upptime_test # Your GitHub repository name

# Add your sites here
sites:
  - name: GTS3.org
    url: https://gts3.org
  - name: Gitlab @ SSLAB
    url: https://gl.gtisc.gatech.edu
  - name: Mattermost
    url: https://mttmst.gtisc.gatech.edu
  - name: Firefox File Send
    url: https://ffs.gtisc.gatech.edu
  - name: taesoo.kim
    url: https://taesoo.kim
  - name: wenke lee
    url: https://wenke.gtisc.gatech.edu
#  - name: Secret Site
#    url: $SECRET_SITE

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime_test
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: SSLAB Status
  introTitle: "SSLAB Status - **Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a SSLAB service status page.
  navbar:
    - title: Status
      href: /upptime_test
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: GTS3.org
      href: https://gts3.org
    - title: Gitlab
      href: https://gl.gtisc.gatech.edu
    - title: Mattermost
      href: https://mttmst.gtisc.gatech.edu

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
